version: "3"
networks:
  mynet:
    driver: overlay

services:
  client:
    image: nherbaut/netcont:latest
    network: mynet
    deploy:
      replicas: 3
    command: iperf -c 172.17.0.2

  server:
    image: nherbaut/netcont:latest
    network: mynet
    deploy:
      replicas: 3
    command: iperf -s -p 5001
    ports:
      - 5000:5001
