version: "3"
networks:
  mynet:
    driver: overlay

services:
  client:
    image: nherbaut/netcont:latest
    networks: 
      - mynet
    deploy:
      replicas: 3
    command: iperf -c {{ salt['mine.get']('vm1', 'network.ip_addrs')['vm1'][0] }}  -p 5000

  server:
    image: nherbaut/netcont:latest
    networks: 
      - mynet
    deploy:
      replicas: 3
    command: iperf -s -p 5001
    ports:
      - 5000:5001
