version: "3"
networks:
  mynet:
    driver: overlay

services:
  client:
    image: nherbaut/netcont:latest
    network: mynet
    deploy:
      replicas: 0
    command: iperf -c 172.17.0.2

  server:
    image: nherbaut/netcont:latest
    network: mynet
    deploy:
      replicas: 0
    command: iperf -s -p 5001
    ports:
      - 5000:5001
  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.3.5
    ports:
      - "8086:8086"
  # Define a Chronograf service
  chronograf:
    image: chronograf:1.3.8
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
