---
configs:
    use: 'libvirt'
    virtualbox:
        minion_count: 0
        base_ip: "192.168.56.%d"
        base_box: "ubuntu/xenial"
        nic_name: "enp0s8"
        cpus: 2
        memory: 2048
    libvirt:
        minion_count: 3
        base_ip: "10.0.56.%d"
        base_box: "generic/ubuntu1604"
        nic_name: "eth1"
        cpus: 2
        memory: 2048
