# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/xenial64"



  config.vm.define "vm1" do |vm1|



     vm1.vm.network :private_network, ip: "192.168.56.101"
     vm1.vm.hostname="vm1"



    vm1.vm.provision "file", source: "../master/.", destination: "/tmp/master"
    vm1.vm.provision "file", source: "../minion/.", destination: "/tmp/minion"

  vm1.vm.provision "shell", inline: <<-SHELL


    echo "192.168.56.101 salt" >> /etc/hosts
    apt-get update
    apt-get install wget
    wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
    echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main" >> /etc/apt/sources.list.d/saltstack.list
    apt-get update
    apt-get install salt-master salt-minion python-pygit2 python-git --yes

    sudo cp -r /tmp/master/* /
    sudo cp -r /tmp/minion/* /


    sudo service salt-master restart
    sudo service salt-minion restart
  SHELL

  end


begin
  (2..2).each do |i|
	  config.vm.define "vm%d" % [ i ] do |node|


	     node.vm.hostname="vm%d" % [i]
	     node.vm.network :private_network, ip: "192.168.56.%d" % [100+i]
       node.vm.provision "file", source: "../minion/.", destination: "/tmp/minion"
	     node.vm.provision "shell", inline: <<-SHELL
             echo "192.168.56.101 salt" >> /etc/hosts
             apt-get update
             apt-get install wget
             wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
             echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main" >> /etc/apt/sources.list.d/saltstack.list
             apt-get update && apt-get install salt-minion python-pygit2 python-git --yes

             sudo cp -r /tmp/minion/* /



             sudo service salt-minion restart
	     SHELL



      end
  end
end
end
